// <auto-generated />
namespace Kendo.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fixprop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixprop));
        
        string IMigrationMetadata.Id
        {
            get { return "202207200609219_fix-prop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
